import { Sparkles, TriangleAlert } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";

export function AiEstimateBadge({ label = "AI estimated" }: { label?: string }) {
  return (
    <Badge variant="muted" className="gap-1 font-normal">
      <Sparkles className="h-3 w-3" />
      {label}
    </Badge>
  );
}

export function OfflineEngineNotice({ context }: { context: string }) {
  return (
    <Alert variant="warning">
      <TriangleAlert />
      <AlertTitle>Generated by the offline engine</AlertTitle>
      <AlertDescription>
        Live AI was unavailable, so {context} was produced by the deterministic offline engine. Add a
        Gemini API key and regenerate for the full language model output. All scores on this page are
        calculated by the application either way.
      </AlertDescription>
    </Alert>
  );
}

export function DemoDataNotice() {
  return (
    <Alert variant="info">
      <Sparkles />
      <AlertTitle>You are exploring demo data</AlertTitle>
      <AlertDescription>
        This account belongs to Aarav Mehta, a fictional candidate created for demonstration. Every
        resume, score, and history item below is sample data, not a real person.
      </AlertDescription>
    </Alert>
  );
}
