import { clamp } from "@/lib/utils";
import type {
  AssessmentPlanPayload,
  CareerExplanationPayload,
  InterviewEvaluationPayload,
  ResumeOptimizationPayload,
  RoadmapPlanPayload,
} from "@/lib/validation/ai";
import type { CareerExplanationContext } from "@/lib/ai/tasks/career-explanation";
import type { RoadmapContext } from "@/lib/ai/tasks/roadmap";
import type { ResumeOptimizerContext } from "@/lib/ai/tasks/resume-optimizer";
import type { AssessmentContext } from "@/lib/ai/tasks/assessment";
import type { InterviewContext } from "@/lib/ai/tasks/interview";
import { normalizeSkillKey } from "./skill-resolver";

export const OFFLINE_NOTICE = "Generated by the offline engine because live AI was unavailable.";

export function fallbackCareerExplanation(
  context: CareerExplanationContext,
): CareerExplanationPayload {
  const strong = context.strongSkills.slice(0, 3).map((skill) => skill.name);
  const gaps = context.gapSkills.slice(0, 3).map((skill) => skill.name);

  const band =
    context.score >= 80
      ? "a strong match"
      : context.score >= 60
        ? "a workable match with focused effort"
        : context.score >= 40
          ? "an achievable stretch"
          : "a longer term target";

  const explanation = [
    `Your profile is ${band} for ${context.roleTitle}.`,
    strong.length > 0
      ? `The score is carried by ${strong.join(", ")}, which map directly onto the weighted requirements for this role.`
      : "No recorded skill currently maps onto the weighted requirements for this role.",
    gaps.length > 0
      ? `The largest deductions come from ${gaps.join(", ")}, where your recorded level sits below the expected level.`
      : "There are no significant weighted gaps left against this role.",
    OFFLINE_NOTICE,
  ].join(" ");

  return {
    explanation,
    strengths:
      strong.length > 0
        ? strong.map((name) => `${name} already meets or approaches the level this role expects.`)
        : ["Add a resume or complete onboarding so strengths can be identified."],
    focusAreas:
      gaps.length > 0
        ? gaps.map((name) => `Raise ${name} toward the level this role requires.`)
        : ["Maintain current skills and deepen breadth across adjacent tools."],
  };
}

const PHASE_TEMPLATES = [
  { title: "Foundations", focus: "Rebuild the fundamentals the rest of the plan depends on." },
  { title: "Core Skill Build", focus: "Work through the highest weighted gaps with daily practice." },
  { title: "Applied Practice", focus: "Use each new skill inside a realistic, scoped exercise." },
  { title: "Integration Project", focus: "Combine the new skills into one portfolio quality build." },
  { title: "Depth and Hardening", focus: "Close remaining gaps and strengthen weaker areas." },
  { title: "Portfolio and Interview Prep", focus: "Package the work and rehearse how you explain it." },
];

export function fallbackRoadmapPlan(context: RoadmapContext): RoadmapPlanPayload {
  const gaps = context.gaps.length > 0 ? context.gaps : [];
  const phaseCount = Math.min(6, Math.max(3, Math.ceil(context.horizonWeeks / 2.5)));
  const weeksPerPhase = Math.max(1, Math.round(context.horizonWeeks / phaseCount));
  const perPhaseHours = Math.max(2, Math.round(context.weeklyHours * weeksPerPhase * 0.4));

  const phases = Array.from({ length: phaseCount }).map((_, phaseIndex) => {
    const template = PHASE_TEMPLATES[Math.min(phaseIndex, PHASE_TEMPLATES.length - 1)];
    const weekStart = Math.min(13, phaseIndex * weeksPerPhase + 1);
    const weekEnd = Math.min(13, Math.max(weekStart, weekStart + weeksPerPhase - 1));
    const isFinal = phaseIndex === phaseCount - 1;
    const assigned = gaps.slice(phaseIndex * 2, phaseIndex * 2 + 2);
    const focusSkill = assigned[0]?.name ?? gaps[phaseIndex % Math.max(1, gaps.length)]?.name;

    const tasks = isFinal
      ? [
          {
            title: "Publish a portfolio write-up for your main project",
            kind: "PROJECT" as const,
            objective: `Document the problem, architecture, and outcome of the project you built for ${context.roleTitle}.`,
            skill: focusSkill,
            estimateHours: Math.min(40, perPhaseHours),
          },
          {
            title: `Rehearse ${context.roleTitle} interview questions`,
            kind: "PRACTICE" as const,
            objective: "Run practice interviews until you can explain every project decision without notes.",
            skill: focusSkill,
            estimateHours: Math.min(40, Math.max(2, Math.round(perPhaseHours * 0.75))),
          },
          {
            title: "Take a skill assessment on your weakest area",
            kind: "ASSESSMENT" as const,
            objective: "Confirm the gap is closed with recorded evidence rather than a resume estimate.",
            skill: gaps[0]?.name,
            estimateHours: 2,
          },
        ]
      : assigned.length > 0
        ? assigned.flatMap((gap) => [
            {
              title: `Study ${gap.name} to level ${gap.requiredLevel}`,
              kind: "LEARN" as const,
              objective: `Move ${gap.name} from an estimated ${gap.currentLevel} toward the ${gap.requiredLevel} this role expects.`,
              skill: gap.name,
              estimateHours: Math.min(40, perPhaseHours),
            },
            {
              title: `Build a small exercise using ${gap.name}`,
              kind: "PRACTICE" as const,
              objective: `Apply ${gap.name} in a scoped exercise so the knowledge survives past the tutorial.`,
              skill: gap.name,
              estimateHours: Math.min(40, Math.max(2, Math.round(perPhaseHours * 0.6))),
            },
          ])
        : [
            {
              title: `Deepen your strongest ${context.roleTitle} skill`,
              kind: "PRACTICE" as const,
              objective: "With no weighted gaps left, convert existing strengths into demonstrable work.",
              skill: context.currentStrengths[0]?.name,
              estimateHours: Math.min(40, perPhaseHours),
            },
          ];

    return {
      title: template.title,
      focus: template.focus,
      weekStart,
      weekEnd,
      tasks: tasks.slice(0, 8),
    };
  });

  return {
    title: `${context.horizonWeeks}-Week Roadmap to ${context.roleTitle}`,
    summary: [
      `A ${context.horizonWeeks} week plan built from your ${gaps.length} recorded skill gaps at ${context.weeklyHours} hours per week.`,
      "Phases are ordered so prerequisite skills come before the skills that build on them.",
      OFFLINE_NOTICE,
    ].join(" "),
    phases,
  };
}

export function fallbackResumeOptimization(
  context: ResumeOptimizerContext,
): ResumeOptimizationPayload {
  const normalizedResume = ` ${normalizeSkillKey(context.resumeText)} `;
  const present = context.roleSkills.filter((skill) =>
    normalizedResume.includes(` ${normalizeSkillKey(skill)} `),
  );
  const missing = context.roleSkills.filter((skill) => !present.includes(skill));
  const keywordCoverage =
    context.roleSkills.length > 0
      ? clamp(Math.round((present.length / context.roleSkills.length) * 100))
      : 0;

  const hasSummary = /\b(summary|profile|objective)\b/i.test(context.resumeText);
  const hasSkillsSection = /\b(skills|technologies|tech stack)\b/i.test(context.resumeText);
  const hasEducation = /\beducation\b/i.test(context.resumeText);
  const hasExperience = /\b(experience|employment)\b/i.test(context.resumeText);
  const hasProjects = /\bprojects?\b/i.test(context.resumeText);

  const sectionsPresent = [hasSummary, hasSkillsSection, hasEducation, hasExperience, hasProjects];
  const sectionCompleteness = clamp(
    Math.round((sectionsPresent.filter(Boolean).length / sectionsPresent.length) * 100),
  );

  const quantified = (context.resumeText.match(/\b\d+(\.\d+)?\s*(%|percent|k\b|m\b|x\b)/gi) ?? []).length;
  const bulletLines = context.resumeText
    .split("\n")
    .filter((line) => /^[-*•]/.test(line.trim()))
    .map((line) => line.replace(/^[-*•]\s*/, "").trim())
    .filter((line) => line.length > 25);

  const formattingWarnings: string[] = [];
  if (/\t/.test(context.resumeText)) {
    formattingWarnings.push("Tab characters were detected, which can misalign text in parsers.");
  }
  if (context.resumeText.split("\n").some((line) => line.length > 220)) {
    formattingWarnings.push("Some lines are very long, which usually indicates multi column layout.");
  }
  if (bulletLines.length < 6) {
    formattingWarnings.push("Fewer than six substantive bullets were found across the document.");
  }
  if (formattingWarnings.length === 0) {
    formattingWarnings.push("No structural formatting problems were detected by the offline parser.");
  }

  const rewrites = bulletLines.slice(0, 4).map((line) => ({
    section: "Experience",
    original: line.slice(0, 600),
    improved: /^[A-Z][a-z]+ed\b/.test(line)
      ? `${line.slice(0, 540)} [add the measurable result, for example time saved or users affected]`
      : `Delivered ${line.charAt(0).toLowerCase()}${line.slice(1, 540)} [add the measurable result]`,
    rationale:
      "Leads with an action verb and reserves an explicit slot for a metric you supply, without inventing one.",
  }));

  return {
    targetAlignmentScore: clamp(Math.round(keywordCoverage * 0.65 + sectionCompleteness * 0.35)),
    atsReadinessScore: clamp(
      Math.round(keywordCoverage * 0.5 + sectionCompleteness * 0.35 + Math.min(15, bulletLines.length)),
    ),
    keywordCoverage,
    sectionCompleteness,
    strengths: [
      present.length > 0
        ? `Your resume already names ${present.length} of the ${context.roleSkills.length} skills this role weights.`
        : "The document parses cleanly, which is the prerequisite for any keyword matching.",
      hasExperience ? "A recognisable experience section is present." : "The document is machine readable.",
      quantified > 0 ? `${quantified} quantified results were detected.` : "Content is concise enough to scan.",
    ],
    weaknesses: [
      missing.length > 0
        ? `${missing.length} weighted skills for this role do not appear anywhere in the text.`
        : "No weighted role skills are missing from the text.",
      hasSummary ? "The summary is present but not tailored to this specific role." : "No summary section was found.",
      quantified < 2 ? "Most bullets describe duties rather than measurable outcomes." : "Impact statements are uneven across roles.",
    ],
    missingKeywords: missing.slice(0, 15),
    formattingWarnings,
    suggestions: [
      {
        section: "Summary",
        issue: hasSummary
          ? "The summary does not name the target role."
          : "There is no summary for a reviewer to anchor on.",
        action: `Open with one line naming ${context.roleTitle} and your two strongest relevant skills.`,
      },
      {
        section: "Skills",
        issue:
          missing.length > 0
            ? `Missing weighted keywords: ${missing.slice(0, 6).join(", ")}.`
            : "The skills section is present and aligned.",
        action:
          missing.length > 0
            ? "Add only the skills you have genuinely used, and back each with a bullet or project."
            : "Keep the skills section ordered by relevance to the target role.",
      },
      {
        section: "Experience",
        issue: "Bullets lead with responsibility rather than outcome.",
        action: "Restructure each bullet as action, method, then result with a number you can defend.",
      },
    ],
    rewrites,
  };
}

export function fallbackAssessment(context: AssessmentContext): AssessmentPlanPayload {
  const skill = context.skillName;
  const templates: AssessmentPlanPayload["questions"] = [
    {
      kind: "SHORT_ANSWER",
      prompt: `Describe the most complex problem you have solved using ${skill}. What made it difficult and how did you approach it?`,
      options: [],
      correctOption: undefined,
      expectedPoints: [
        "A specific problem rather than a generic description",
        "The approach or technique chosen",
        "Why that approach was appropriate",
        "The outcome or what was learned",
      ],
      explanation: "Strong answers name a concrete situation and justify the technical choice.",
    },
    {
      kind: "PRACTICAL",
      prompt: `A teammate says their ${skill} work is producing incorrect results but they cannot reproduce it locally. Walk through how you would diagnose this.`,
      options: [],
      correctOption: undefined,
      expectedPoints: [
        "Reproducing the failure reliably before changing anything",
        "Isolating the difference between environments",
        "Using logs, tests, or instrumentation as evidence",
        "Confirming the fix and preventing regression",
      ],
      explanation: "Strong answers show a systematic debugging loop rather than guesswork.",
    },
    {
      kind: "SHORT_ANSWER",
      prompt: `What are the most common mistakes people make when they are new to ${skill}, and how do you avoid them?`,
      options: [],
      correctOption: undefined,
      expectedPoints: [
        "At least two concrete mistakes",
        "Why each mistake causes problems",
        "A practical habit that prevents it",
      ],
      explanation: "This surfaces depth of practical exposure beyond tutorial knowledge.",
    },
    {
      kind: "PRACTICAL",
      prompt: `You need to teach ${skill} to a colleague in thirty minutes. What do you cover, in what order, and what do you deliberately leave out?`,
      options: [],
      correctOption: undefined,
      expectedPoints: [
        "A prioritised sequence of concepts",
        "Reasoning about prerequisites",
        "An explicit decision about what to omit",
      ],
      explanation: "Being able to sequence a topic is a reliable proxy for understanding it.",
    },
    {
      kind: "SHORT_ANSWER",
      prompt: `How would you decide whether ${skill} is the right tool for a new project, and what would make you choose something else?`,
      options: [],
      correctOption: undefined,
      expectedPoints: [
        "Concrete selection criteria",
        "Awareness of trade-offs and limits",
        "A named alternative and when it wins",
      ],
      explanation: "Strong answers show judgement rather than advocacy.",
    },
    {
      kind: "PRACTICAL",
      prompt: `Describe how you would test work built with ${skill} so that a regression is caught before release.`,
      options: [],
      correctOption: undefined,
      expectedPoints: [
        "Types of tests and what each covers",
        "What is worth testing and what is not",
        "How the tests run automatically",
      ],
      explanation: "Testing strategy separates production experience from practice projects.",
    },
    {
      kind: "SHORT_ANSWER",
      prompt: `What would you need to learn next to move from your current level of ${skill} to an expert level?`,
      options: [],
      correctOption: undefined,
      expectedPoints: [
        "An honest assessment of the current level",
        "Specific named topics, not vague intentions",
        "A realistic way to practise them",
      ],
      explanation: "Accurate self assessment is itself a signal of competence.",
    },
    {
      kind: "PRACTICAL",
      prompt: `Explain a ${skill} decision you would make differently today than you did when you first learned it.`,
      options: [],
      correctOption: undefined,
      expectedPoints: [
        "A specific earlier decision",
        "What changed in the person's understanding",
        "The reasoning behind the new approach",
      ],
      explanation: "Reflection on past decisions indicates real accumulated practice.",
    },
  ];

  return {
    title: `${skill} Practice Assessment`,
    questions: templates.slice(0, Math.min(Math.max(context.questionCount, 3), 8)),
  };
}

export function heuristicGradeOpenAnswer(answer: string, expectedPoints: string[]) {
  const cleaned = answer.trim();
  if (cleaned.length < 15) {
    return { scorePercent: 0, feedback: "The answer is too short to demonstrate the expected points." };
  }

  const normalizedAnswer = ` ${normalizeSkillKey(cleaned)} `;
  const covered = expectedPoints.filter((point) => {
    const keywords = normalizeSkillKey(point)
      .split(" ")
      .filter((word) => word.length > 4);
    if (keywords.length === 0) return false;
    const hits = keywords.filter((word) => normalizedAnswer.includes(word)).length;
    return hits / keywords.length >= 0.34;
  });

  const coverageRatio = expectedPoints.length > 0 ? covered.length / expectedPoints.length : 0;
  const wordCount = cleaned.split(/\s+/).filter(Boolean).length;
  const depthBonus = Math.min(20, Math.round(wordCount / 6));
  const specificityBonus = /\b\d/.test(cleaned) ? 8 : 0;

  const scorePercent = clamp(Math.round(coverageRatio * 62 + depthBonus + specificityBonus));

  const missed = expectedPoints.filter((point) => !covered.includes(point));
  const feedback =
    missed.length > 0
      ? `Offline grading matched ${covered.length} of ${expectedPoints.length} expected points. Still to address: ${missed.slice(0, 3).join("; ")}.`
      : `Offline grading matched all ${expectedPoints.length} expected points. Add a concrete example with numbers to strengthen it further.`;

  return { scorePercent, feedback };
}

const INTERVIEW_OPENERS: Record<string, string[]> = {
  TECHNICAL: [
    "Walk me through the architecture of the most technically demanding thing you have built. What were the constraints?",
    "Describe a bug that took you more than a day to find. How did you eventually track it down?",
    "How do you decide when a piece of code needs to be refactored rather than extended?",
  ],
  BEHAVIORAL: [
    "Tell me about a time you disagreed with a decision on your team. What did you do?",
    "Describe a project that did not go the way you expected. What would you change?",
    "Tell me about a time you had to learn something unfamiliar under time pressure.",
  ],
  MIXED: [
    "Tell me about a project you are proud of, and walk me through one technical decision you made in it.",
    "Describe a time you had to deliver something with an incomplete specification. How did you proceed?",
    "What is the most useful thing you have learned in the last six months, and how did you apply it?",
  ],
};

export function fallbackInterviewQuestion(context: InterviewContext, askedCount: number) {
  const pool = INTERVIEW_OPENERS[context.kind] ?? INTERVIEW_OPENERS.MIXED;
  const base = pool[askedCount % pool.length];
  if (askedCount === 0) return base;

  const focus = context.focusSkills[(askedCount - 1) % Math.max(1, context.focusSkills.length)];
  if (!focus) return base;
  return `${base.replace(/\?$/, "")} Where relevant, ground your answer in your experience with ${focus}.`;
}

const STRUCTURE_MARKERS = [
  "first",
  "then",
  "next",
  "finally",
  "because",
  "so that",
  "as a result",
  "the problem",
  "my role",
  "the outcome",
];

export function fallbackInterviewEvaluation(
  context: InterviewContext,
  answer: string,
  askedCount: number,
): InterviewEvaluationPayload {
  const cleaned = answer.trim();
  const words = cleaned.split(/\s+/).filter(Boolean);
  const wordCount = words.length;
  const lower = cleaned.toLowerCase();

  const structureHits = STRUCTURE_MARKERS.filter((marker) => lower.includes(marker)).length;
  const skillHits = context.focusSkills.filter((skill) =>
    lower.includes(skill.toLowerCase()),
  ).length;
  const hasNumbers = /\d/.test(cleaned);
  const hasFirstPerson = /\bi\b/.test(lower);

  const completeness = clamp(Math.round(Math.min(100, (wordCount / 140) * 100)));
  const structure = clamp(30 + structureHits * 12 + (hasFirstPerson ? 10 : 0));
  const relevance = clamp(38 + skillHits * 14 + (wordCount > 40 ? 14 : 0));
  const technicalAccuracy = clamp(34 + skillHits * 12 + (hasNumbers ? 12 : 0) + (wordCount > 90 ? 10 : 0));
  const communication = clamp(
    40 + (wordCount > 60 ? 15 : 0) + structureHits * 8 - (wordCount > 420 ? 12 : 0),
  );

  const strengths: string[] = [];
  const improvements: string[] = [];

  if (wordCount >= 90) strengths.push("The answer has enough detail to evaluate.");
  if (structureHits >= 2) strengths.push("The response follows a recognisable narrative structure.");
  if (hasNumbers) strengths.push("Concrete numbers make the impact verifiable.");
  if (skillHits > 0) strengths.push("The answer stays anchored to skills relevant to the role.");
  if (strengths.length === 0) strengths.push("You engaged with the question directly.");

  if (wordCount < 60) improvements.push("Expand the answer: aim for 90 to 180 words with a concrete example.");
  if (structureHits < 2) improvements.push("Use a situation, action, result structure so the listener can follow.");
  if (!hasNumbers) improvements.push("Quantify the outcome, even approximately.");
  if (skillHits === 0 && context.focusSkills.length > 0) {
    improvements.push(`Name the specific technologies involved, such as ${context.focusSkills.slice(0, 2).join(" or ")}.`);
  }
  if (improvements.length === 0) improvements.push("Tighten the opening so the core result lands in the first sentence.");

  return {
    relevance,
    technicalAccuracy,
    structure,
    communication,
    completeness,
    feedback: [
      `Offline evaluation scored this answer on length, structure, specificity, and role relevance.`,
      improvements[0],
      OFFLINE_NOTICE,
    ].join(" "),
    strengths: strengths.slice(0, 4),
    improvements: improvements.slice(0, 4),
    followUpQuestion: fallbackInterviewQuestion(context, askedCount),
  };
}
