"use client";

import { useState } from "react";
import {
  ArrowRight,
  BadgeCheck,
  FileWarning,
  Loader2,
  ScanLine,
  Sparkles,
  TriangleAlert,
  Wand2,
} from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Progress } from "@/components/ui/progress";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { ScoreRing } from "@/components/shared/score-ring";
import { ErrorPanel } from "@/components/shared/error-panel";
import { postJson } from "@/lib/api/client";
import type { ResumeOptimizationPayload } from "@/lib/validation/ai";

type OptimizeResponse = {
  roleTitle: string;
  report: ResumeOptimizationPayload;
  usedFallback: boolean;
};

export function OptimizerPanel({
  roles,
  defaultRoleId,
}: {
  roles: Array<{ id: string; title: string; score: number | null }>;
  defaultRoleId: string;
}) {
  const [roleId, setRoleId] = useState(defaultRoleId);
  const [pending, setPending] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [response, setResponse] = useState<OptimizeResponse | null>(null);

  const run = async () => {
    if (!roleId) {
      setError("Select a target career role first.");
      return;
    }

    setPending(true);
    setError(null);

    const result = await postJson<OptimizeResponse>("/api/resume/optimize", {
      careerRoleId: roleId,
    });

    setPending(false);

    if (!result.ok) {
      setError(result.message);
      return;
    }

    setResponse(result.data);
  };

  const report = response?.report;

  return (
    <div className="space-y-4">
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Wand2 className="h-4 w-4 text-muted-foreground" />
            Review against a target role
          </CardTitle>
          <CardDescription>
            Rewrites only rephrase what is already in your resume. Missing metrics become placeholders
            you fill in, never invented numbers.
          </CardDescription>
        </CardHeader>

        <CardContent className="space-y-5">
          {error ? <ErrorPanel message={error} onRetry={run} /> : null}

          <div className="flex flex-col gap-3 sm:flex-row sm:items-end">
            <div className="flex-1 space-y-2">
              <Label htmlFor="optimizer-role">Target role</Label>
              <Select value={roleId} onValueChange={setRoleId}>
                <SelectTrigger id="optimizer-role">
                  <SelectValue placeholder="Select a role" />
                </SelectTrigger>
                <SelectContent>
                  {roles.map((role) => (
                    <SelectItem key={role.id} value={role.id}>
                      {role.title}
                      {role.score !== null ? ` — ${role.score}%` : ""}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <Button onClick={run} disabled={pending}>
              {pending ? <Loader2 className="animate-spin" /> : <ScanLine />}
              {pending ? "Analyzing resume" : "Run optimization"}
            </Button>
          </div>
        </CardContent>
      </Card>

      {response?.usedFallback ? (
        <Alert variant="warning">
          <TriangleAlert />
          <AlertTitle>Generated by the offline engine</AlertTitle>
          <AlertDescription>
            Live AI was unavailable, so this review was produced by the deterministic keyword and
            structure analyser. Scores are calculated the same way either way.
          </AlertDescription>
        </Alert>
      ) : null}

      {report ? (
        <>
          <Card>
            <CardHeader>
              <CardTitle>ATS Readiness Score</CardTitle>
              <CardDescription>
                A measure of how well this resume parses and aligns with {response?.roleTitle}. It is not
                a compatibility claim about any specific vendor&apos;s applicant tracking system.
              </CardDescription>
            </CardHeader>
            <CardContent className="grid gap-6 sm:grid-cols-4">
              <div className="flex flex-col items-center gap-2">
                <ScoreRing
                  value={report.atsReadinessScore}
                  size={104}
                  label="ATS ready"
                  tone={report.atsReadinessScore >= 70 ? "success" : "warning"}
                />
              </div>
              <div className="flex flex-col items-center gap-2">
                <ScoreRing
                  value={report.targetAlignmentScore}
                  size={104}
                  label="Role fit"
                  tone={report.targetAlignmentScore >= 70 ? "success" : "warning"}
                />
              </div>
              <div className="space-y-2 sm:col-span-2">
                <div className="space-y-1.5">
                  <div className="flex items-center justify-between text-sm">
                    <span className="text-muted-foreground">Keyword coverage</span>
                    <span className="font-medium tabular-nums">{report.keywordCoverage}%</span>
                  </div>
                  <Progress value={report.keywordCoverage} className="h-1.5" />
                </div>
                <div className="space-y-1.5">
                  <div className="flex items-center justify-between text-sm">
                    <span className="text-muted-foreground">Section completeness</span>
                    <span className="font-medium tabular-nums">{report.sectionCompleteness}%</span>
                  </div>
                  <Progress value={report.sectionCompleteness} className="h-1.5" />
                </div>
              </div>
            </CardContent>
          </Card>

          <div className="grid gap-4 lg:grid-cols-3">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <BadgeCheck className="h-4 w-4 text-success" />
                  Strengths
                </CardTitle>
              </CardHeader>
              <CardContent>
                <ul className="space-y-2.5">
                  {report.strengths.map((item) => (
                    <li key={item} className="flex gap-2.5 text-sm leading-relaxed">
                      <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-success" />
                      {item}
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <TriangleAlert className="h-4 w-4 text-warning" />
                  Weaknesses
                </CardTitle>
              </CardHeader>
              <CardContent>
                <ul className="space-y-2.5">
                  {report.weaknesses.map((item) => (
                    <li key={item} className="flex gap-2.5 text-sm leading-relaxed">
                      <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-warning" />
                      {item}
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <FileWarning className="h-4 w-4 text-muted-foreground" />
                  Formatting warnings
                </CardTitle>
              </CardHeader>
              <CardContent>
                <ul className="space-y-2.5">
                  {report.formattingWarnings.map((item) => (
                    <li key={item} className="flex gap-2.5 text-sm leading-relaxed">
                      <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-border" />
                      {item}
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>
          </div>

          {report.missingKeywords.length > 0 ? (
            <Card>
              <CardHeader>
                <CardTitle>Missing keywords</CardTitle>
                <CardDescription>
                  Skills this role weights that do not appear in your resume text. Only add the ones you
                  have genuinely used.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="flex flex-wrap gap-2">
                  {report.missingKeywords.map((keyword) => (
                    <Badge key={keyword} variant="warning" className="font-normal">
                      {keyword}
                    </Badge>
                  ))}
                </div>
              </CardContent>
            </Card>
          ) : null}

          {report.suggestions.length > 0 ? (
            <Card>
              <CardHeader>
                <CardTitle>Improvement suggestions</CardTitle>
                <CardDescription>Section by section, what to change and why.</CardDescription>
              </CardHeader>
              <CardContent className="space-y-3">
                {report.suggestions.map((suggestion, index) => (
                  <div key={index} className="rounded-lg border p-4">
                    <Badge variant="secondary" className="mb-2 font-normal">
                      {suggestion.section}
                    </Badge>
                    <p className="text-sm leading-relaxed text-muted-foreground">{suggestion.issue}</p>
                    <p className="mt-2 flex gap-2 text-sm leading-relaxed">
                      <ArrowRight className="mt-0.5 h-4 w-4 shrink-0 text-primary" />
                      {suggestion.action}
                    </p>
                  </div>
                ))}
              </CardContent>
            </Card>
          ) : null}

          {report.rewrites.length > 0 ? (
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Sparkles className="h-4 w-4 text-primary" />
                  Rewritten examples
                </CardTitle>
                <CardDescription>
                  Each rewrite is built only from content already present in your resume.
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                {report.rewrites.map((rewrite, index) => (
                  <div key={index} className="space-y-2">
                    <Badge variant="secondary" className="font-normal">
                      {rewrite.section}
                    </Badge>

                    <div className="grid gap-2 md:grid-cols-2">
                      <div className="rounded-lg border border-destructive/25 bg-destructive/5 p-3">
                        <p className="mb-1 text-[11px] font-semibold uppercase tracking-wider text-destructive">
                          Original
                        </p>
                        <p className="text-sm leading-relaxed text-muted-foreground">
                          {rewrite.original}
                        </p>
                      </div>
                      <div className="rounded-lg border border-success/25 bg-success/5 p-3">
                        <p className="mb-1 text-[11px] font-semibold uppercase tracking-wider text-success">
                          Improved
                        </p>
                        <p className="text-sm leading-relaxed">{rewrite.improved}</p>
                      </div>
                    </div>

                    <p className="text-xs leading-relaxed text-muted-foreground">
                      {rewrite.rationale}
                    </p>
                  </div>
                ))}
              </CardContent>
            </Card>
          ) : null}
        </>
      ) : null}
    </div>
  );
}
